import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // `dark` ships on the server render so dark is the default (locked
      // 2026-05-08) with no light flash. The boot script below may remove it
      // before paint if the user has stored a light preference.
      className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        {/* bm-design-system:start */}
        {/* Runs before paint, so a stored preference never flashes. Mirrors
            DEFAULT_THEME in lib/theme.ts — keep the two in sync. */}
        <script
          id="theme-boot"
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var s=localStorage.getItem('bm-ds-theme');var t=(s==='light'||s==='dark'||s==='system')?s:'dark';var r=t==='system'?(window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):t;var c=document.documentElement.classList;if(r==='dark')c.add('dark');else c.remove('dark');}catch(e){}})();`,
          }}
        />
        {/* bm-design-system:end */}
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
